[project]
name = "agent-one"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.7.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "prompt-toolkit>=3.0.0",
    "anyio>=4.9.0",
]
